### ISSUE TITLE
Group is created but users are not

### ISSUE THREAD

**Issue by michielbdejong** [SURFnet/rd-sram-integration#190] opened 2023-06-09 11:56 UTC
See https://github.com/SURFnet/rd-sram-integration/issues/184#issuecomment-1584221776

**Comment by michielbdejong** [comment] 2023-06-09 14:22
This was due to database replication. If Tom removes the db proxy then this problem goes away.
To fix it in general (so that it also works with a db proxy) we should use the cache in the group backend.
We fill it here: https://github.com/SURFnet/rd-sram-integration/blob/2207762/federatedgroups/lib/GroupBackend.php#L97
But we don't read it here: 
https://github.com/SURFnet/rd-sram-integration/blob/2207762/federatedgroups/lib/GroupBackend.php#L148

**Comment by navid-shokri** [comment] 2023-06-09 19:09
can we close this Issue? 
@michielbdejong

**Comment by thepeak99** [comment] 2023-06-12 14:46
The customer wants to use it with a DB cluster. We have to check that it works.

**Comment by thepeak99** [comment] 2023-06-13 11:03
We should not assume that our inserts will pop up in subsequent selects. 

Also we need to create a test for this.

**Comment by thepeak99** [comment] 2023-06-23 10:40
duplicate of #197

**Closed by thepeak99** 2023-06-23 10:40 UTC
Labels: milestone 1.1
